### ISSUE TITLE
Terraform Plan Status does not fail workflow after Terraform 1.4 release

### ISSUE THREAD

**Issue by audunsolemdal** [hashicorp/learn-terraform-github-actions#1081]
Previosuly the github action would fail if the terraform plan failed. After these changes it seems like some rewrites are needed, although it is not obvious what the fix would be

```
The Terraform plan renderer has been completely rewritten to aid with future Terraform Cloud integration. Users should not see any material change in the plan output between 1.3 and 1.4. If you notice any significant differences, or if Terraform fails to plan successfully due to rendering problems, please open a bug report issue.
```

Step which now fails
```
- name: Terraform Plan Status
  if: steps.plan.outcome == 'failure'
  run: exit 1
```

New output from plan step if tfplan fails:

```
Planning failed. Terraform encountered an error while generating this plan.
```

**Comment by judithpatudith** [comment]
Thanks for the report! We're looking into it!

**Comment by audunsolemdal** [comment]
@judithpatudith any status update on this?

**Comment by alanszlosek** [comment]
Hi @audunsolemdal , we're no longer using this repo since we recently updated the tutorial and the GitHub Actions workflows it uses. Find the new one here: https://github.com/hashicorp-education/learn-terraform-github-actions

The tutorial and workflows have changed quite a bit, so hopefully the changes fix the issues you were having.

Which reminds me, I need to update this repo's readme to point folks to the new one. :-) 

Thanks for reporting.
